-- MySQL Script generated by MySQL Workbench
-- Thu Mar 30 23:03:10 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema footballDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema footballDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `footballDB` DEFAULT CHARACTER SET utf8 ;
USE `footballDB` ;

-- -----------------------------------------------------
-- Table `footballDB`.`Role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `footballDB`.`Role` ;

CREATE TABLE IF NOT EXISTS `footballDB`.`Role` (
  `roleID` INT NOT NULL AUTO_INCREMENT,
  `roleName` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`roleID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `footballDB`.`State`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `footballDB`.`State` ;

CREATE TABLE IF NOT EXISTS `footballDB`.`State` (
  `idState` INT NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idState`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `footballDB`.`Team`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `footballDB`.`Team` ;

CREATE TABLE IF NOT EXISTS `footballDB`.`Team` (
  `teamID` INT NOT NULL AUTO_INCREMENT,
  `teamName` VARCHAR(20) NOT NULL,
  `NFA` VARCHAR(60) NULL,
  `acronym` VARCHAR(10) NULL,
  `nickname` VARCHAR(45) NULL,
  `State_idState` INT NOT NULL,
  PRIMARY KEY (`teamID`),
  INDEX `fk_Team_State1_idx` (`State_idState` ASC),
  CONSTRAINT `fk_Team_State1`
    FOREIGN KEY (`State_idState`)
    REFERENCES `footballDB`.`State` (`idState`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `footballDB`.`Competitor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `footballDB`.`Competitor` ;

CREATE TABLE IF NOT EXISTS `footballDB`.`Competitor` (
  `competitorID` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(3) NOT NULL,
  `firstName` VARCHAR(20) NOT NULL,
  `lastName` VARCHAR(20) NULL,
  `Role_roleID` INT NOT NULL,
  `Team_teamID` INT NOT NULL,
  PRIMARY KEY (`competitorID`),
  INDEX `fk_Competitor_Role1_idx` (`Role_roleID` ASC),
  INDEX `fk_Competitor_Team1_idx` (`Team_teamID` ASC),
  CONSTRAINT `fk_Competitor_Role1`
    FOREIGN KEY (`Role_roleID`)
    REFERENCES `footballDB`.`Role` (`roleID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Competitor_Team1`
    FOREIGN KEY (`Team_teamID`)
    REFERENCES `footballDB`.`Team` (`teamID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `footballDB`.`Card`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `footballDB`.`Card` ;

CREATE TABLE IF NOT EXISTS `footballDB`.`Card` (
  `cardID` INT NOT NULL AUTO_INCREMENT,
  `startDate` DATE NOT NULL,
  `endDate` DATE NOT NULL,
  `Competitor_competitorID` INT NOT NULL,
  `State_idState` INT NOT NULL,
  `Team_teamID` INT NOT NULL,
  PRIMARY KEY (`cardID`, `Competitor_competitorID`),
  INDEX `fk_Card_Competitor1_idx` (`Competitor_competitorID` ASC),
  INDEX `fk_Card_State1_idx` (`State_idState` ASC),
  INDEX `fk_Card_Team1_idx` (`Team_teamID` ASC),
  CONSTRAINT `fk_Card_Competitor1`
    FOREIGN KEY (`Competitor_competitorID`)
    REFERENCES `footballDB`.`Competitor` (`competitorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Card_State1`
    FOREIGN KEY (`State_idState`)
    REFERENCES `footballDB`.`State` (`idState`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Card_Team1`
    FOREIGN KEY (`Team_teamID`)
    REFERENCES `footballDB`.`Team` (`teamID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `footballDB`.`Venue`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `footballDB`.`Venue` ;

CREATE TABLE IF NOT EXISTS `footballDB`.`Venue` (
  `venueID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`venueID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `footballDB`.`Match`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `footballDB`.`Match` ;

CREATE TABLE IF NOT EXISTS `footballDB`.`Match` (
  `no` INT(2) NOT NULL,
  `date` DATE NOT NULL,
  `stadium` VARCHAR(45) NULL,
  `Team_teamID` INT NOT NULL,
  `Team_teamID1` INT NOT NULL,
  `Venue_venueID` INT NOT NULL,
  INDEX `fk_Match_Team1_idx` (`Team_teamID` ASC),
  INDEX `fk_Match_Team2_idx` (`Team_teamID1` ASC),
  INDEX `fk_Match_Venue1_idx` (`Venue_venueID` ASC),
  PRIMARY KEY (`no`),
  CONSTRAINT `fk_Match_Team1`
    FOREIGN KEY (`Team_teamID`)
    REFERENCES `footballDB`.`Team` (`teamID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Match_Team2`
    FOREIGN KEY (`Team_teamID1`)
    REFERENCES `footballDB`.`Team` (`teamID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Match_Venue1`
    FOREIGN KEY (`Venue_venueID`)
    REFERENCES `footballDB`.`Venue` (`venueID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `footballDB`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `footballDB`.`Users` ;

CREATE TABLE IF NOT EXISTS `footballDB`.`Users` (
  `loginID` INT NOT NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `permission` TINYINT NULL,
  PRIMARY KEY (`loginID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `footballDB`.`Entry`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `footballDB`.`Entry` ;

CREATE TABLE IF NOT EXISTS `footballDB`.`Entry` (
  `entryID` INT NOT NULL AUTO_INCREMENT,
  `Card_cardID` INT NOT NULL,
  `Date` DATE NOT NULL,
  `Match_no` INT(2) NOT NULL,
  `Stadium` VARCHAR(50) NOT NULL,
  `Venue_venueID` INT NOT NULL,
  `State_idState` INT NOT NULL,
  PRIMARY KEY (`entryID`),
  INDEX `fk_Log_Card1_idx` (`Card_cardID` ASC),
  INDEX `fk_Log_Match1_idx` (`Match_no` ASC),
  INDEX `fk_Entry_Venue1_idx` (`Venue_venueID` ASC),
  INDEX `fk_Entry_State1_idx` (`State_idState` ASC),
  CONSTRAINT `fk_Log_Card1`
    FOREIGN KEY (`Card_cardID`)
    REFERENCES `footballDB`.`Card` (`cardID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Log_Match1`
    FOREIGN KEY (`Match_no`)
    REFERENCES `footballDB`.`Match` (`no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Entry_Venue1`
    FOREIGN KEY (`Venue_venueID`)
    REFERENCES `footballDB`.`Venue` (`venueID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Entry_State1`
    FOREIGN KEY (`State_idState`)
    REFERENCES `footballDB`.`State` (`idState`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `footballDB`.`Authorisation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `footballDB`.`Authorisation` ;

CREATE TABLE IF NOT EXISTS `footballDB`.`Authorisation` (
  `AuthID` INT NOT NULL AUTO_INCREMENT,
  `Card_cardID` INT NOT NULL,
  `date` DATE NOT NULL,
  `Venue_venueID` INT NOT NULL,
  `Match_no` INT(2) NOT NULL,
  `State_idState` INT NOT NULL,
  INDEX `fk_Card_has_Match_Card1_idx` (`Card_cardID` ASC),
  INDEX `fk_Authorisation_Venue1_idx` (`Venue_venueID` ASC),
  INDEX `fk_Authorisation_Match1_idx` (`Match_no` ASC),
  INDEX `fk_Authorisation_State1_idx` (`State_idState` ASC),
  PRIMARY KEY (`AuthID`),
  CONSTRAINT `fk_Card_has_Match_Card1`
    FOREIGN KEY (`Card_cardID`)
    REFERENCES `footballDB`.`Card` (`cardID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Authorisation_Venue1`
    FOREIGN KEY (`Venue_venueID`)
    REFERENCES `footballDB`.`Venue` (`venueID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Authorisation_Match1`
    FOREIGN KEY (`Match_no`)
    REFERENCES `footballDB`.`Match` (`no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Authorisation_State1`
    FOREIGN KEY (`State_idState`)
    REFERENCES `footballDB`.`State` (`idState`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
