-- MySQL Script generated by MySQL Workbench
-- Fri Feb 24 18:42:16 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema footballDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema footballDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `footballDB` DEFAULT CHARACTER SET utf8 ;
USE `footballDB` ;

-- -----------------------------------------------------
-- Table `footballDB`.`team`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `footballDB`.`team` ;

CREATE TABLE IF NOT EXISTS `footballDB`.`team` (
  `teamID` INT NOT NULL AUTO_INCREMENT,
  `teamName` VARCHAR(20) NULL,
  `NFA` VARCHAR(45) NULL,
  `acronym` VARCHAR(10) NULL,
  `nickname` VARCHAR(45) NULL,
  PRIMARY KEY (`teamID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `footballDB`.`competitor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `footballDB`.`competitor` ;

CREATE TABLE IF NOT EXISTS `footballDB`.`competitor` (
  `competitorID` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(3) NULL,
  `firstName` VARCHAR(20) NULL,
  `lastName` VARCHAR(20) NULL,
  `role` VARCHAR(45) NULL,
  `team_teamID` INT NOT NULL,
  PRIMARY KEY (`competitorID`),
  INDEX `fk_competitor_team1_idx` (`team_teamID` ASC),
  CONSTRAINT `fk_competitor_team1`
    FOREIGN KEY (`team_teamID`)
    REFERENCES `footballDB`.`team` (`teamID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `footballDB`.`venue`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `footballDB`.`venue` ;

CREATE TABLE IF NOT EXISTS `footballDB`.`venue` (
  `venueID` INT NOT NULL AUTO_INCREMENT,
  `venueNames` VARCHAR(45) NULL,
  `date` DATE NULL,
  `team_teamID` INT NOT NULL,
  PRIMARY KEY (`venueID`),
  INDEX `fk_venue_team1_idx` (`team_teamID` ASC),
  CONSTRAINT `fk_venue_team1`
    FOREIGN KEY (`team_teamID`)
    REFERENCES `footballDB`.`team` (`teamID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `footballDB`.`cards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `footballDB`.`cards` ;

CREATE TABLE IF NOT EXISTS `footballDB`.`cards` (
  `cardID` INT NOT NULL AUTO_INCREMENT,
  `competitor_competitorID` INT NOT NULL,
  `startDate` DATE NULL,
  `endDate` DATE NULL,
  `cardState` TINYINT NULL,
  `venue_venueID` INT NOT NULL,
  PRIMARY KEY (`cardID`),
  INDEX `fk_cards_competitor_idx` (`competitor_competitorID` ASC),
  INDEX `fk_cards_venue1_idx` (`venue_venueID` ASC),
  CONSTRAINT `fk_cards_competitor`
    FOREIGN KEY (`competitor_competitorID`)
    REFERENCES `footballDB`.`competitor` (`competitorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cards_venue1`
    FOREIGN KEY (`venue_venueID`)
    REFERENCES `footballDB`.`venue` (`venueID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `footballDB`.`matches`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `footballDB`.`matches` ;

CREATE TABLE IF NOT EXISTS `footballDB`.`matches` (
  `matchID` INT NOT NULL AUTO_INCREMENT,
  `no` INT NULL,
  `date` DATE NULL,
  `team1` VARCHAR(45) NULL,
  `team2` VARCHAR(45) NULL,
  `stadium` VARCHAR(45) NULL,
  `competitor_competitorID` INT NOT NULL,
  `venue_venueID` INT NOT NULL,
  `team_teamID` INT NOT NULL,
  PRIMARY KEY (`matchID`),
  INDEX `fk_matches_competitor1_idx` (`competitor_competitorID` ASC),
  INDEX `fk_matches_venue1_idx` (`venue_venueID` ASC),
  INDEX `fk_matches_team1_idx` (`team_teamID` ASC),
  CONSTRAINT `fk_matches_competitor1`
    FOREIGN KEY (`competitor_competitorID`)
    REFERENCES `footballDB`.`competitor` (`competitorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matches_venue1`
    FOREIGN KEY (`venue_venueID`)
    REFERENCES `footballDB`.`venue` (`venueID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matches_team1`
    FOREIGN KEY (`team_teamID`)
    REFERENCES `footballDB`.`team` (`teamID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `footballDB`.`logs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `footballDB`.`logs` ;

CREATE TABLE IF NOT EXISTS `footballDB`.`logs` (
  `logID` INT NOT NULL AUTO_INCREMENT,
  `time` DATETIME NULL,
  `duration` INT NULL,
  `cards_cardID` INT NOT NULL,
  `venue_venueID` INT NOT NULL,
  PRIMARY KEY (`logID`, `venue_venueID`),
  INDEX `fk_logs_cards1_idx` (`cards_cardID` ASC),
  INDEX `fk_logs_venue1_idx` (`venue_venueID` ASC),
  CONSTRAINT `fk_logs_cards1`
    FOREIGN KEY (`cards_cardID`)
    REFERENCES `footballDB`.`cards` (`cardID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_logs_venue1`
    FOREIGN KEY (`venue_venueID`)
    REFERENCES `footballDB`.`venue` (`venueID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `footballDB`.`authorisations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `footballDB`.`authorisations` ;

CREATE TABLE IF NOT EXISTS `footballDB`.`authorisations` (
  `access` TINYINT NULL,
  `matches_matchID` INT NOT NULL,
  `venue_venueID` INT NOT NULL,
  `cards_cardID` INT NOT NULL,
  INDEX `fk_authorisations_matches1_idx` (`matches_matchID` ASC),
  INDEX `fk_authorisations_venue1_idx` (`venue_venueID` ASC),
  INDEX `fk_authorisations_cards1_idx` (`cards_cardID` ASC),
  CONSTRAINT `fk_authorisations_matches1`
    FOREIGN KEY (`matches_matchID`)
    REFERENCES `footballDB`.`matches` (`matchID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_authorisations_venue1`
    FOREIGN KEY (`venue_venueID`)
    REFERENCES `footballDB`.`venue` (`venueID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_authorisations_cards1`
    FOREIGN KEY (`cards_cardID`)
    REFERENCES `footballDB`.`cards` (`cardID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `footballDB`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `footballDB`.`users` ;

CREATE TABLE IF NOT EXISTS `footballDB`.`users` (
  `loginID` INT NOT NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `permission` TINYINT NULL,
  PRIMARY KEY (`loginID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
