-- MySQL Script generated by MySQL Workbench
-- Fri Mar 10 16:52:12 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema footballDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema footballDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `footballDB` DEFAULT CHARACTER SET utf8 ;
USE `footballDB` ;

-- -----------------------------------------------------
-- Table `footballDB`.`Venue`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `footballDB`.`Venue` ;

CREATE TABLE IF NOT EXISTS `footballDB`.`Venue` (
  `venueID` INT NOT NULL AUTO_INCREMENT,
  `venueNames` VARCHAR(45) NULL,
  PRIMARY KEY (`venueID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `footballDB`.`Match`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `footballDB`.`Match` ;

CREATE TABLE IF NOT EXISTS `footballDB`.`Match` (
  `matchID` INT NOT NULL AUTO_INCREMENT,
  `no` NCHAR(2) NULL,
  `date` DATE NULL,
  `stadium` VARCHAR(45) NULL,
  `Team_teamID` INT NOT NULL,
  `Team_teamID1` INT NOT NULL,
  `Venue_venueID` INT NOT NULL,
  PRIMARY KEY (`matchID`, `Venue_venueID`),
  INDEX `fk_Match_Team1_idx` (`Team_teamID` ASC),
  INDEX `fk_Match_Team2_idx` (`Team_teamID1` ASC),
  INDEX `fk_Match_Venue1_idx` (`Venue_venueID` ASC),
  CONSTRAINT `fk_Match_Team1`
    FOREIGN KEY (`Team_teamID`)
    REFERENCES `footballDB`.`Team` (`teamID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Match_Team2`
    FOREIGN KEY (`Team_teamID1`)
    REFERENCES `footballDB`.`Team` (`teamID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Match_Venue1`
    FOREIGN KEY (`Venue_venueID`)
    REFERENCES `footballDB`.`Venue` (`venueID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `footballDB`.`Team`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `footballDB`.`Team` ;

CREATE TABLE IF NOT EXISTS `footballDB`.`Team` (
  `teamID` INT NOT NULL AUTO_INCREMENT,
  `teamName` VARCHAR(20) NULL,
  `NFA` VARCHAR(60) NULL,
  `acronym` VARCHAR(10) NULL,
  `nickname` VARCHAR(45) NULL,
  `state` NCHAR(1) NULL,
  `Match_matchID` INT NOT NULL,
  PRIMARY KEY (`teamID`),
  INDEX `fk_Team_Match1_idx` (`Match_matchID` ASC),
  CONSTRAINT `fk_Team_Match1`
    FOREIGN KEY (`Match_matchID`)
    REFERENCES `footballDB`.`Match` (`matchID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `footballDB`.`Card`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `footballDB`.`Card` ;

CREATE TABLE IF NOT EXISTS `footballDB`.`Card` (
  `cardID` INT NOT NULL AUTO_INCREMENT,
  `startDate` DATE NULL,
  `endDate` DATE NULL,
  `cardState` TINYINT NULL,
  `Competitor_competitorID` INT NOT NULL,
  PRIMARY KEY (`cardID`),
  INDEX `fk_Card_Competitor1_idx` (`Competitor_competitorID` ASC),
  CONSTRAINT `fk_Card_Competitor1`
    FOREIGN KEY (`Competitor_competitorID`)
    REFERENCES `footballDB`.`Competitor` (`competitorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `footballDB`.`Role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `footballDB`.`Role` ;

CREATE TABLE IF NOT EXISTS `footballDB`.`Role` (
  `roleID` INT NOT NULL,
  `roleName` VARCHAR(20) NULL,
  PRIMARY KEY (`roleID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `footballDB`.`Competitor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `footballDB`.`Competitor` ;

CREATE TABLE IF NOT EXISTS `footballDB`.`Competitor` (
  `competitorID` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(3) NULL,
  `firstName` VARCHAR(20) NULL,
  `lastName` VARCHAR(20) NULL,
  `team_teamID` INT NOT NULL,
  `Card_cardID` INT NOT NULL,
  `Role_roleID` INT NOT NULL,
  PRIMARY KEY (`competitorID`),
  INDEX `fk_competitor_team1_idx` (`team_teamID` ASC),
  INDEX `fk_Competitor_Card1_idx` (`Card_cardID` ASC),
  INDEX `fk_Competitor_Role1_idx` (`Role_roleID` ASC),
  CONSTRAINT `fk_competitor_team1`
    FOREIGN KEY (`team_teamID`)
    REFERENCES `footballDB`.`Team` (`teamID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Competitor_Card1`
    FOREIGN KEY (`Card_cardID`)
    REFERENCES `footballDB`.`Card` (`cardID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Competitor_Role1`
    FOREIGN KEY (`Role_roleID`)
    REFERENCES `footballDB`.`Role` (`roleID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `footballDB`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `footballDB`.`Users` ;

CREATE TABLE IF NOT EXISTS `footballDB`.`Users` (
  `loginID` INT NOT NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `permission` TINYINT NULL,
  PRIMARY KEY (`loginID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `footballDB`.`Log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `footballDB`.`Log` ;

CREATE TABLE IF NOT EXISTS `footballDB`.`Log` (
  `logID` INT NOT NULL,
  `Match_matchID` INT NOT NULL,
  `Card_cardID` INT NOT NULL,
  PRIMARY KEY (`logID`),
  INDEX `fk_Log_Match1_idx` (`Match_matchID` ASC),
  INDEX `fk_Log_Card1_idx` (`Card_cardID` ASC),
  CONSTRAINT `fk_Log_Match1`
    FOREIGN KEY (`Match_matchID`)
    REFERENCES `footballDB`.`Match` (`matchID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Log_Card1`
    FOREIGN KEY (`Card_cardID`)
    REFERENCES `footballDB`.`Card` (`cardID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `footballDB`.`Authorisation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `footballDB`.`Authorisation` ;

CREATE TABLE IF NOT EXISTS `footballDB`.`Authorisation` (
  `authorisationID` INT NOT NULL,
  `Card_cardID` INT NOT NULL,
  `Match_matchID` INT NOT NULL,
  `state` NCHAR(1) NULL,
  `date` DATE NULL,
  PRIMARY KEY (`authorisationID`),
  INDEX `fk_Card_has_Match_Match1_idx` (`Match_matchID` ASC),
  INDEX `fk_Card_has_Match_Card1_idx` (`Card_cardID` ASC),
  CONSTRAINT `fk_Card_has_Match_Card1`
    FOREIGN KEY (`Card_cardID`)
    REFERENCES `footballDB`.`Card` (`cardID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Card_has_Match_Match1`
    FOREIGN KEY (`Match_matchID`)
    REFERENCES `footballDB`.`Match` (`matchID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `footballDB`.`Bugs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `footballDB`.`Bugs` ;

CREATE TABLE IF NOT EXISTS `footballDB`.`Bugs` (
  `bugID` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `subject` VARCHAR(20) NULL,
  `description` VARCHAR(200) NULL,
  PRIMARY KEY (`bugID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
